baseURL = "http://dbkernel.github.io/"
languageCode = "en-us"
theme = "hugo-theme-yelee"

disablePathToLower = true

[params]
author = "卢文双"
title = "卢文双的博客"
subtitle = "专注于介绍关系型数据库及分布式数据库的技术内幕、实现原理。"
root_url = "/"
avatar = "img/avatar.png"
tagcloud = true
aboutme = "资深数据库技术专家。目前从事云数据库MySQL/PostgreSQL的研发工作，曾做过PGXC、Greenplum等分布式数据库的内核开发。热衷于研究主流数据库架构、源码，对关系型数据库 MySQL/PostgreSQL及分布式数据库有深入研究。"
jquery_ui = false
mathjax = false
background_image = 5
google_analytics = ""
fancybox = true
open_in_new = true
animate = false

[params.friends]
"知乎" = "https://zhuanlan.zhihu.com/mysqldb"
"segmentfault" = "https://segmentfault.com/u/dbtech"
"oschina" = "https://my.oschina.net/dbtech"
"掘金" = "https://juejin.im/user/5e9d3ed251882538083fed1f/posts"
"博客园" = "https://www.cnblogs.com/dbtech/"

[params.subnav]
Email = "mailto:wenshuang_lu@163.com"
GitHub = "https://github.com/DBKernel"

[[params.menu]]
label = "主页"
link = "/"

[[params.menu]]
label = "所有文章"
link = "/post/"

[[params.menu]]
label = "标签"
link = "/tags/"

[[params.menu]]
label = "关于我"
link = "/about/"

[params.visit_counter]
on = true
site_visit = "本站到访数"
page_visit = "本页阅读量"
